pygments: true
safe: true
markdown: kramdown
highlighter: pygments
baseurl: /
itle: Practice Python
author: 
  name: Michele Pratusevich
  email: michele.pratusevich@gmail.com
production_url: http://practicepython.org