lsi: false
safe: true
markdown: kramdown
highlighter: rouge
baseurl: ""
title: Practice Python
author: 
  name: Michele Pratusevich
  email: michele.pratusevich@gmail.com
twitter:
  username: practice_python
production_url: http://practicepython.org
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from